<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.payment.export.platform</groupId>
        <artifactId>payment-export-service</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>payment-export-service-container</artifactId>
    <packaging>jar</packaging>

    <name>Payment Export Service - Web Api</name>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.payment.export.platform</groupId>
            <artifactId>payment-export-service-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.payment.export.platform</groupId>
            <artifactId>payment-export-service-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.payment.export.platform</groupId>
            <artifactId>payment-export-service-persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>com.payment.export.platform</groupId>
            <artifactId>payment-export-service-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>com.payment.export.platform</groupId>
            <artifactId>payment-export-service-integration</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
